### ISSUE TITLE
Сделать фикстуры для каждого приложения.

### ISSUE THREAD

**Issue by Reagent992** [Reagent992/ipr-hackathon-yandex-alfa#31]
Делаем папку ./docs/fixture и туда зальем фикстуры, отдельно для каждой модели.
Команда: `python -Xutf8 manage.py dumpdata название_приложения.название_модели  --indent=2 --output  docs/fixture/название_файла.json` # вставить свое.
`-Xutf8` добавляет поддержку русского языка
`--indent=2` делает фикстуру "человеко-читаемой".
https://docs.djangoproject.com/en/4.2/ref/django-admin/#django-admin-dumpdata

- [x] Для Users. 
- [x] Для Tasks. 
- [x] Для IPR.
- [ ] Возможно для Ratings.
- [x] Для уведомлений в конце, когда остальные готовы будут. ( Похоже для уведомлений ненужны фикстуры, они создаются автоматически при добавление остальных. )

**Comment by IlyaKotenko** [comment]
### Superadmin
Login: superadmin@m-mail.com
Pass: Password

### Пользователи:

Руководители команд:
sheremetev.boris@idp-test.com
razumovskij.aleksej@idp-test.com
orlov.grigorij@idp-test.com

Сотрудники:
menshikov.aleksandr@idp-test.com
rumyanceva.mariya@idp-test.com
shuvalov.ivan@idp-test.com
kantemir.mariya@idp-test.com
potyomkin.grigorij@idp-test.com
voroncova.elizaveta@idp-test.com

Пароль для всех: upass
